package com.vanillaci.api.controller;

import com.vanillaci.api.*;
import org.apache.log4j.*;
import org.springframework.amqp.rabbit.core.*;
import org.springframework.beans.factory.annotation.*;
import org.springframework.stereotype.*;
import org.springframework.web.bind.annotation.*;

import java.util.concurrent.atomic.*;

/**
 * @author Joel Johnson
 */
@Controller
public class JobController {
	private Logger log = Logger.getLogger(JobController.class);

	@Autowired
	private AppConfiguration appConfiguration;

	@SuppressWarnings("SpringJavaAutowiringInspection")
	@Autowired
	RabbitTemplate rabbitTemplate;

	private AtomicInteger atomicInteger = new AtomicInteger();

	@RequestMapping("/startJob")
	@ResponseBody
	public int startJob() {
		log.info("Starting job");

		int workId = atomicInteger.incrementAndGet(); // TODO: persist a "Build" object and use the ID generated by the DB

		String message = "{\"id\":"+workId+"}";

		rabbitTemplate.convertAndSend(appConfiguration.getQueueName(), message);

		return workId;
	}
}
