package com.vanillaci.api.controller;

import com.vanillaci.api.*;
import com.vanillaci.api.model.*;
import com.vanillaci.api.service.*;
import org.apache.log4j.*;
import org.springframework.amqp.rabbit.core.*;
import org.springframework.beans.factory.annotation.*;
import org.springframework.stereotype.*;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.atomic.*;

/**
 * @author Joel Johnson
 */
@Controller
@RequestMapping(value = "/job", method = RequestMethod.GET, produces = "application/json")
public class JobController {
	private Logger log = Logger.getLogger(JobController.class);

	@Autowired
	private AppConfiguration appConfiguration;

	@SuppressWarnings("SpringJavaAutowiringInspection")
	@Autowired
	private RabbitTemplate rabbitTemplate;

	@Autowired
	private JobService jobService;

	private AtomicInteger atomicInteger = new AtomicInteger();

	@RequestMapping(value = "/{id}/start", method = RequestMethod.POST)
	@ResponseBody
	public int startJob(@PathVariable("id") Long id, @RequestBody Map<String, String> parameters) {
		log.info("Starting job");

		int workId = atomicInteger.incrementAndGet(); // TODO: persist a "Build" object and use the ID generated by the DB

		String message = "{\"id\":"+workId+"}";

		rabbitTemplate.convertAndSend(appConfiguration.getQueueName(), message);

		return workId;
	}

	@RequestMapping(method = RequestMethod.POST)
	@ResponseBody
	public Job createJob(@RequestBody Job job) {
		job = jobService.createJob(job);
		return job;
	}
}
